### PR TITLE
Menu Sub-Theme Styles

### LINKED ISSUE #330: Main Menu Navigation Style
Since we are moving away from separate themes to a single theme, we need to add in the ability to change the appearance/style of  the main menu navigation on sites. In addition to being able to choose a brand bar color and site name color, users should also be able to choose a menu style.

Below are screenshots of a site in each theme showing what a main menu item looks like when that's the current page:

Screen Shot 2023-04-18 at 3 11 52 PM
Screen Shot 2023-04-18 at 3 14 08 PM
Screen Shot 2023-04-18 at 3 13 54 PM
Screen Shot 2023-04-18 at 3 13 39 PM
Screen Shot 2023-04-18 at 3 13 24 PM
Screen Shot 2023-04-18 at 3 13 09 PM
Screen Shot 2023-04-18 at 3 12 53 PM
Screen Shot 2023-04-18 at 3 12 40 PM
Screen Shot 2023-04-18 at 3 12 26 PM
Screen Shot 2023-04-18 at 3 12 14 PM
Screen Shot 2023-04-18 at 3 12 02 PM

### PR DESCRIPTION
**Pull request by jacob-korf**
Closes #330.
Work in collaboration with siteconfiguration/#24.
Adds 11 new menu styles to the base theme of the boulder theme.

### CODE REVIEW

**Comment by TeddyBearX** [comment]
Screenshot 2023-06-20 at 2 55 01 PM
The bottom menu shouldn't be impacted by these styles, here it appears to have more padding than usual. The font size for some of these styles is also maybe a bit too big compared to Kevin's screenshots. Kevin's screenshot for [this one](https://user-images.githubusercontent.com/349713/232908244-5e8f0870-6009-4f76-8d87-11034875cc6a.png) for reference. Spirit, Highlight, and Ivory have border issues still.

**Comment by TeddyBearX** [comment]
Then again the font size isn't really an issue to me. I actually find Kevin's screenshot a bit hard to read with the links on the side. Can let him decide on that one. Probably a good idea to add some padding to make the "iMac Timeline" link look  not as close to the edge.

**Comment by TeddyBearX** [comment]
A previous comment mentioned issues with the "Simple" menu style but I fixed those myself. Spirit, Highlight, and Ivory have border issues still.

**Comment by TeddyBearX** [comment]
"Layers" menu should have a `#272727` background color. "Rise" is missing the box-shadow. Otherwise this is good enough to merge.

**Review by TeddyBearX — APPROVED** [review]

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
