### PR TITLE
Article Lists: Hides Dates, Decodes Special Characters in Titles of Taxonomy Term Pages

### LINKED ISSUE #1429: Article list based on taxonomy terms shows author date even though hiding it on articles
The Article List page generated for taxonomy terms shows the article authoring dates for each article, even though the Date/Time/Formatting was set to Hide Date/Time for each article. 

D7 taxonomy article page: https://www.colorado.edu/transfer-admissions
Screenshot 2024-10-23 at 11 16 33 AM

D10 taxonomy article page: https://live-ucbdev-homepage.pantheonsite.io/admissions/transfer-admissions
Screenshot 2024-10-23 at 11 17 19 AM

### PR DESCRIPTION
**Pull request by jacob-korf**
If an Article has it's date set to 'Hide' this update will hide the date on `Category` and `Tag` Taxonomy pages as well as on the `Article List Page` and `Article List Block` displays that show the date (Teaser, Feature)

Additionally fixes the display of special characters on Taxonomy term pages from not decoding correctly.

Resolves https://github.com/CuBoulder/tiamat-theme/issues/1465
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1429
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1509

Profile -> https://github.com/CuBoulder/tiamat10-profile/pull/239

### CODE REVIEW

**Comment by patrickbrown-io** [comment]
Thanks Jacob! I will add in the fixes for other Article aggregators as well and ping for review when ready

**Comment by jcsparks** [comment]
I'm still seeing the dates on the Article List Block as well as the on the Taxonomy views.

**Comment by patrickbrown-io** [comment]
Need to use global setting on Article Aggregator blocks. We might be able to tap into this on a view using a preprocess function, but need to test what's possible.

**Comment by patrickbrown-io** [comment]
@jacob-korf This is a new issue, maybe we could address in this ticket too: https://github.com/CuBoulder/tiamat-theme/issues/1509

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
