### PR TITLE
Newsletter: Moves social links from Node to Newsletter term

### LINKED ISSUE #867: Newsletter: Social Links Refactor
Need to modify the social links: Remove them from the page and tie them to the taxonomy term. ~~They have a lot more configuration than we do:~~

~~- Social Links Label~~
~~- Social Links Title~~
~~- Body~~

- ~~Link paragraph field:~~
   - Type (list of social media sites)
   ~~- The URL~~
~~- Icon Arrangement (Horizonal Icons Only, Horizontal w Text, Vertical w Text)~~
~~- Icon Size (24, 32, 48, 64)~~
~~- Homepage URL~~

EDIT: Most of this config is thrown away, d7 reuses a social block. Icons are fixed size, fixed arrangement with no lables and all other fields are dumped. Just need to move the links from pulling the social media menu to fixed per newsletter term

### PR DESCRIPTION
**Pull request by patrickbrown-io**
Resolves #867 

Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/871
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/130

### CODE REVIEW

**Review by timurtripp — CHANGES_REQUESTED** [review]
Remove "tweet.com", this is not needed. Also remove the `title` attribute, I don't think email clients care, neither Apple Mail nor Outlook seem to respect it.

**Comment by timurtripp** [comment]
Actually keep `title` it may be useful for accessibility

**Comment by timurtripp** [comment]
You may want to fix the capitalization of it though.

**Comment by timurtripp** [comment]
You actually don't need `title` if your image has an `alt` associated with it. The `alt` will suffice.

**Comment by timurtripp** [comment]
I don't think it hurts anything though

**Comment by patrickbrown-io** [comment]
> I don't think it hurts anything though

I use it to insert the correct color service in the JS, which handles the src formatting and the alt tag

**Comment by timurtripp** [comment]
Give this a look over

**Comment by patrickbrown-io** [comment]
> Give this a look over

Looks the same, success

**Comment by timurtripp** [comment]
Cool 👍 I did notice one more minor bug which is the "Social link" text never shows up, for normal links it's still the lowercase "link".

**Review by timurtripp — APPROVED** [review]

**Pull request merged**
