### PR TITLE
Video Reveal and Hero Fix

### LINKED ISSUE #1250: Video Reveal blocks don't reveal and play video when play button is clicked.
Something changed with the video reveal blocks where clicking the play icon doesn't reveal and play the video. There is no javascript error associated with this in the console.

Here's some examples:

https://www.colorado.edu/aerospace/admissions
https://www.colorado.edu/aerospace/about-us
https://www.colorado.edu/demos/documentation/block-content/video-reveal-block

### PR DESCRIPTION
**Pull request by jnicholCU**
Both the video reveal and hero unit needed to have the `load` option changed to `DOMContentLoaded` because of GTM scripts interfering with the normal functions of our video scripts. 

This fixes the loading errors that both of them had for youtube. Vimeo is still working as intended. The change I had asked David to test didn't seem to work so this is the current fix for the issue other than fully removing the social trackers that are breaking it. Unfortunately not an option currently.

When testing the Video Hero Unit seems to be overriding the Video Reveal's functionality so they cannot be on the same page. This looks to be happening even with the current version so it's not a new bug. I'm going to create a new ticket for that issue. I haven't been able to figure out what is actually causing the problem but I think it has to do with the youtube iframe api being loaded twice.

Resolves #1250

### CODE REVIEW

**Review by timurtripp — CHANGES_REQUESTED** [review]
Issue is not fixed for me, Video Reveal block still not responding to clicks. I've cleared caches and verified in the source code that `DOMContentLoaded` shows up.

**Comment by jnicholCU** [comment]
Wild. That's frustrating. I had it working in every browser I tried. Going to see if others are having issues still as well.

**Comment by jnicholCU** [comment]
The `defer` addition might have it working.

**Review by timurtripp — CHANGES_REQUESTED** [review]
No change with `defer`.

**Pull request closed without merging**
