### PR TITLE
Block Alignments

### LINKED ISSUE #847: Content alignment in multi-column sections
Multi-column sections have additional horizontal padding, resulting in the content on the left not aligning with content that is placed in a single column section.

image

### PR DESCRIPTION
**Pull request by jnicholCU**
Made fixes to layout alignment so that blocks will always be synced.
The main thing is that the left edge and right edge of the row content should align properly. 
There are very slight deviations in the 3 and 4 column options but those are normal for how css handles rows more than 2 columns. (The D7 version has the same discrepancies) 

Test by making tones of rows with different combos of frames and background colors with various different block types

Sister PR: https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/43

Resolves #847 

image
image
image
image

### CODE REVIEW

**Comment by timurtripp** [comment]
There seems to be a lot of space below the title, more than I remember there being before.
Screenshot 2024-05-30 at 2 38 13 PM

**Comment by jnicholCU** [comment]
> There seems to be a lot of space below the title, more than I remember there being before. 

Oh yeah I meant to mention that. I'll be changing the spacing there once I've got some information from Kevin. He's still deciding how much he's wanting there and below each block. This PR is mainly about the alignment. There is extra spacing now because the body content needed the `block` class because it had 0 spacing around it which was looking bad on their sandboxes.

**Comment by timurtripp** [comment]
Alright. On my install it looks fine but I don't have any multicolumn regions at the moment so I'll have to create some.

**Comment by timurtripp** [comment]
Another potential spacing issue I'm seeing
Screenshot 2024-05-30 at 2 53 18 PM

**Comment by patrickbrown-io** [comment]
Form block, happens on all column layouts:
Screenshot 2024-05-30 at 3 05 25 PM

**Comment by jnicholCU** [comment]
> Another potential spacing issue I'm seeing 

Spacing between blocks in a column is still something I'm waiting on answers from Kevin for.

**Comment by jnicholCU** [comment]
> Form block, happens on all column layouts: 

Good catch. I'll get that sorted.

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
