### PR TITLE
Events Calendar |raw removal

### LINKED ISSUE #842: Events Calendar block |raw change
`|raw` needs to be removed from the rendering of this block
`|render` should work for the logic check
`|t` should work for the embed rendering

### PR DESCRIPTION
**Pull request by jnicholCU**
Remove `|raw` loading.
Replace localist widget ID with randomly generated ID Strip query strings from embed input.
Hardcode embed div and js using new ID and query parameters

Resolves #842

### CODE REVIEW

**Review by timurtripp — CHANGES_REQUESTED** [review]
I have the embed code
```html
<script type="text/javascript" src="https://calendar.colorado.edu/widget/view?schools=ucboulder&num=50&days=160&match=any&hideimage=1&template=express-template-2&types=115168,113533,115167,115256,113536,115163,113541,113537,113546,113548&show_types=0&express-cc=1615583707"></script>
```
Seems to be working [here in the developer sandbox](https://www.colorado.edu/developer-sandbox/advanced-block-test-page) but not in this branch.

**Comment by jnicholCU** [comment]
Looks like it's because I left the `defer` in the script. Going to take that out.

**Comment by jnicholCU** [comment]
That looks to be working now using that script. Let me know if you have issues still.

**Comment by timurtripp** [comment]
That fixed the problem, the only question I have left is if there is a way to get some sort of existing id rather than calling `random()`.

**Comment by jnicholCU** [comment]
The ids already randomize on each widget generate so I thought it'd be quicker just to replace it rather than scrape it out. 
That said I was wanting to use the block ID rather than using `random()` but for whatever reason I was getting duplicate block IDs on my local environment so they were conflicting if there was more than one calendar. 
Was doing it the exact same way we handle the expands and sliders but I was still getting duplicate IDs.

**Comment by timurtripp** [comment]
Is `element['#object'].id.value` doing that for you?

**Comment by timurtripp** [comment]
That does create a conflict if there are two instances of the same reusable block on the same page, hmm. Is this ever a situation that could happen?

**Comment by jnicholCU** [comment]
I'm sure there is a situation someone could conjure up where they'd have 2 of the same reusable blocks on a page. I didn't even consider that case for the other blocks. I'm going to be sure and test that to see what problems could arise. 

The weird thing here though is I'm not using reusable blocks for these calendars but for some reason my first two always have the same ID. The third one is different though. For the life of me I couldn't figure out why. I don't have this problem with any other blocks.

image

**Comment by jnicholCU** [comment]
Using `random()` does keep it from being a problem for reusable blocks at the very least.
image

**Comment by timurtripp** [comment]
Alright. I guess using `random()` is fine. My only concern is this changing value being treated as a page update somewhere in the cache pipeline but I'm not entirely sure if this is a valid concern or not. In my early iterations of Bootstrap Accordion I had a similar call but I made the decision not to risk it and instead have the id generated once at accordion creation time.

**Comment by jnicholCU** [comment]
That's a good point. Might be something worth discussing as a group too.

**Review by timurtripp — APPROVED** [review]

**Comment by jnicholCU** [comment]
Changed out `random()` to `|clean_unique_id` because it is a truly unique ID for every block that renders even if it's reusable on the same page.

**Comment by timurtripp** [comment]
Update version requirement to Drupal 10.1 or later in the `boulder_base.info.yml`.

**Review by timurtripp — APPROVED** [review]

**Pull request merged**
