### PR TITLE
Improves styling of the "Expandable Content" block type

### PR DESCRIPTION
**Pull request by TeddyBearX**
This update includes bug fixes and stylistic changes to the "Expandable Content" block type to address recent feedback.

Resolves CuBoulder/tiamat-theme#401

Resolves CuBoulder/tiamat-theme#402

Resolves CuBoulder/tiamat-theme#404

Resolves CuBoulder/tiamat-theme#405

Resolves CuBoulder/tiamat-theme#422

### CODE REVIEW

**Comment by jcsparks** [comment]
If the first item isn't set to be open is should still display as a plus icon to open it.  

Screenshot 2023-06-27 at 11 10 46 AM

**Comment by jcsparks** [comment]
I'm getting accordions nested inside the tabs now in the desktop view 
Screenshot 2023-06-27 at 1 01 00 PM

And big gaps between elements in the accordion in mobile view 
Screenshot 2023-06-27 at 1 01 44 PM

**Comment by TeddyBearX** [comment]
Is your CSS up-to-date?

**Comment by TeddyBearX** [comment]
To troubleshoot cached CSS – SHIFT + Reload or test in a different browser. In some cases you may also need to clear the Drupal caches.

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
