### PR TITLE
Adds `web_express_version` theme variable

### PR DESCRIPTION
**Pull request by timurtripp**
[new] Resolves CuBoulder/tiamat-theme#1274

### CODE REVIEW

**Comment by jcsparks** [comment]
Where's the rest of the code?  You've got it pulling the variable but you haven't allocated storage for it or pulled a settings config file to edit it in the profile?

**Comment by jcsparks** [comment]
Can you move the string to the bottom of the column as well, just put it after the documentation link please.

**Comment by timurtripp** [comment]
Can move it below the documentation link, that's fine. I'm not entirely sure what you're asking for with the settings config since theme variables aren't set or modified by the profile at all. I can give it a default for new sites but figured that'll just be overridden anyway.

**Comment by jcsparks** [comment]
https://www.drupal.org/docs/8/theming-drupal-8/creating-advanced-theme-settings

It should be exportable into `boulder_base.settigns.yml` like the other theme variables that are set.

**Comment by timurtripp** [comment]
Yeah that's just setting a default value for new sites, e.g. an empty string. It doesn't affect any existing sites.

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
