### PR TITLE
Updates regions

### LINKED ISSUE #819: Blocks placed in Above Content region via block layout should be aligned with other content in the region
When a block is placed in the above content region, the block gets aligned to the left edge of the page rather than being placed in the center and aligned with the other content on the page. This leaves a blank space on the right side of the page:

image

Looks like this is also due to the icon block styles getting applied at the block level instead of on the icon:
image

### LINKED ISSUE #896: Layout Builder admin template
Layout Builder currently gets all of the other regions tacked onto it's view when doing admin work
i.e. if something is added to the above content or sidebar region it is displayed within the layout builder

This is the case even if you add exceptions to where the regions show up. So if you say a sidebar should not show up on the About page, and then edit the about page in Layout Builder, that sidebar will show up in the admin view despite not showing up on the front facing About page.

Solve this by adding a new Layout Builder node layout template

### PR DESCRIPTION
**Pull request by jnicholCU**
This update:
- [Bug] Adds proper containers to above and below content, fixing incorrect margins. Resolves #819
- [Change, Remove] Adds template for Layout Builder pages. Removes above content, breadcrumbs, sidebar, and below content regions from Layout Builder pages. Resolves #896
- [Remove] Removes above content region from search, taxonomy, user, and 403 pages. Resolves CuBoulder/tiamat-theme#877

### CODE REVIEW

**Comment by timurtripp** [comment]
We switched from tabs to spaces in accordance with the Drupal coding standards. Do not change it back.

**Comment by jnicholCU** [comment]
Oh yep that's my bad. Was wondering why my vs formatter was changing so much there.

**Comment by timurtripp** [comment]
You have a formatter for Twig files? I haven't gotten mine to work properly for Twig.

**Comment by jnicholCU** [comment]
I found one for Twig 2/3 formatting which had worked fine with 2 space indents. But now I'm seeing every time I format it's just adding 2 extra spaces and not actually formatting. I just formatted 5 times in a row and all my code is super far to the right now lol. 

Tested changing the indentation setting and it's still doing it. Definitely a bug.

**Comment by jnicholCU** [comment]
Fixed the formatting in the new commit. Just reverted back and added the code in again manually fixing it's format as needed.

**Comment by timurtripp** [comment]
The indentation is still tabs on the code you added. If you select the text in VS Code, it'll show you which one it is. Or you can search for tabs in the search box.

**Comment by timurtripp** [comment]
What types of blocks are we putting in the above and below content?

**Comment by jnicholCU** [comment]
Any block can be put in those two sections.

**Comment by timurtripp** [comment]
Alright, I'm wondering because I'm still seeing some margining issues. This is a Social Media Icons block placed in the Above Content region.
Screenshot 2024-04-23 at 1 35 24 PM

**Comment by timurtripp** [comment]
Probably don't want any static margin/padding for the section, but you could try something like a CSS first child selector.

**Comment by jnicholCU** [comment]
I see the slight indent on the text for the social media, is this because of the region or something in the block though? 
image

**Comment by timurtripp** [comment]
The block has no margin at the top and is right up against the nav bar.

**Comment by timurtripp** [comment]
That's the only issue visible in my screenshot, everything else looks fine.

**Comment by jnicholCU** [comment]
Oh gotcha. I'll ping Kevin about how much padding/margin we should have for that and create a separate issue. There have been a couple talks around upper and lower spacing so I want to make sure we're all on the same page first.

**Comment by timurtripp** [comment]
Do you know why there are two after content regions?

**Comment by timurtripp** [comment]
Still has inconsistent behavior on some more obscure pages like search, taxonomy, and 403 pages. I'd recommend creating a template under the `regions` folder and putting the proper container div there instead.

**Comment by jnicholCU** [comment]
The container div isn't inside the region though. It's containing the region.
You're right about functionality though. This problem already exists so we should probably discuss it as a team. 

> Do you know why there are two after content regions?

As for this, there is a wide version and a contained version. Just as there is for the above content. (Above content is labeled post wide title)

**Comment by jnicholCU** [comment]
Yeah we should just discuss some of this as a team because it's not just a problem with those two regions. Every extra region is breaking stuff in multiple places if content is added.

**Comment by timurtripp** [comment]
> The container div isn't inside the region though. It's containing the region.

If you're putting the region inside the same container for every place it's rendered, then the container should just be in the region template. We've done that for some of our other regions.

**Comment by jnicholCU** [comment]
> > The container div isn't inside the region though. It's containing the region.
> 
> If you're putting the region inside the same container for every place it's rendered, then the container should just be in the region template. We've done that for some of our other regions.

Right, the thing is it's actually only supposed to be rendered on that `page.html.twig`
I forgot that I'm going to be out tomorrow so I hopped onto a call with Jeremy and Mike to talk about it. 
We're going to remove the {{ above.content }} from the other layouts because it doesn't need to be there. 
I also need to add the alerts banner to all those layouts as we determined that should be on everything. 
Finally I added a layout for the layout builder so that it only shows the relevant information/preview for that instead of adding every which region. 
That should clear up the problems that we're running into.

**Comment by jnicholCU** [comment]
I guess I should say determining a place for the status messages is part of this. The post wide title might be the correct choice. Just haven't had a decision made yet.

**Comment by timurtripp** [comment]
Is this ready for review?

**Review by timurtripp — APPROVED** [review]

**Review by patrickbrown-io — APPROVED** [review]
Above and below content margins look good. These and other regions successfully removed from specific pages and layout builder

**Pull request merged**
