### PR TITLE
Remove all menu hashes

### LINKED ISSUE #1536: URL hash fragment being applied when clicking nav links
Something annoying I've noticed is that whenever I open a mega menu or click a link in one of the site's navigation menus, I get a URL hash fragment appended on the page's URL. This isn't how it worked in D7 and ends up filling my browser history with a bunch of duplicate entries which go to the same page.

I think this was originally developed for accordion / expandable content in PR CuBoulder/tiamat-theme#1473 and isn't supposed to apply to site navigation menus, so I'm marking it as a bug.

Screenshot_20241209_102014

### PR DESCRIPTION
**Pull request by jacob-korf**
Resolves #1536
Removes all mentions to menus and the functionality of a hash being added to menus.

### CODE REVIEW

**Comment by jcsparks** [comment]
@timurtripp - review and merge in if that looks good to you.

**Comment by timurtripp** [comment]
Looking at Josh's original PR, it looks like it's supposed to work on "expandable block's accordion/horizontal/vertical options" and this no longer applies to the horizontal/vertical options if the goal is to push the hash onto the page URL for those.

But I'm not actually sure why we need these hashes appended to the page URL to begin with, even for accordion / expandable content. Someone can just right-click on the accordion button or tab and easily get the hash that way. I personally find this to be a very annoying feature which results in lots of duplicate browser history entries whenever I interact with accordions, and I vote to just remove it completely.

I'd like to bring @jnicholCU into the discussion.

**Comment by jnicholCU** [comment]
Yeah the hashes still need to appear when clicking on any of the accordions and this does break the vertical and horizontal. I must have gone too wide with my net though and it started grabbing all the hashes in the menus too. 
I do agree that the hash in the address bar seems like something we don't need. However UI/UX asked for it because that's how the D7 sites functioned.

**Comment by timurtripp** [comment]
My 6 clicks on the browser back button to go back to the previous page definitely disagree with them...

**Comment by timurtripp** [comment]
I'll take that up with them but in the meantime @jacob-korf ensure the behavior doesn't change for the vertical and horizontal expandable content. Thanks.

**Review by timurtripp — CHANGES_REQUESTED** [review]
See above

**Review by timurtripp — APPROVED** [review]

**Pull request merged**
