### PR TITLE
Update region--site-information.html.twig

### LINKED ISSUE #490: Footer line spacing
There is too much space between the lines in the footer.

### PR DESCRIPTION
**Pull request by jnicholCU**
Changed class name to fix styling error.

Closes #490

### CODE REVIEW

**Review by timurtripp — CHANGES_REQUESTED** [review]
Something still seems off about our footer's spacing. I've attached a side-by-side comparison which might help us spot any issues with margin/padding.

D7:
Screen Shot 2023-09-22 at 8 55 06 AM

D10:
Screen Shot 2023-09-22 at 8 54 49 AM

**Comment by timurtripp** [comment]
It seems like there is insufficient padding around the "Be Boulder" slogan.

**Comment by jnicholCU** [comment]
From commit: 
Added padding to the be boulder image
Leaving the other spacing alone in the site info section because that meets requirements given by Kevin even though it's not a match to the current D7 instance.

**Review by timurtripp — CHANGES_REQUESTED** [review]
The footer should have padding at the top to match the D7 version and make it more proportionate to the padding at the bottom.

**Review by timurtripp — APPROVED** [review]

**Pull request merged**
