### PR TITLE
Adjusts spacing between sibling blocks within a column

### LINKED ISSUE #820: Too much spacing between blocks in sections
Within sections, when multiple blocks are stacked in that section, there is too much vertical space between them. 

Example: Academic page
Current page: https://www.colorado.edu/academics/bs-aerospace-engineering
Sandbox page: https://live-ucbdev-sandbox-wendy.pantheonsite.io/bachelor-science-aerospace-engineering

Main block:
Current:
Screenshot 2024-04-11 at 9 42 59 AM
Sandbox:
Screenshot 2024-04-11 at 9 42 53 AM
Screenshot 2024-04-11 at 9 46 12 AM

Be successful block:
Current:
Screenshot 2024-04-11 at 9 50 09 AM
Sandbox:
Screenshot 2024-04-11 at 9 50 17 AM

Screenshot 2024-04-11 at 9 50 49 AM

### PR DESCRIPTION
**Pull request by patrickbrown-io**
Resolves #820

### CODE REVIEW

**Comment by timurtripp** [comment]
Is there a reason you added it to both stylesheets and not just the layout builder styles?

**Comment by timurtripp** [comment]
I noticed there's still a lot of margin on a wrapped multi-column view on mobile devices. It behaves just like the single-column view on D7 (same amount of margin) so I'm afraid this may come up as an issue. What are your thoughts on this?
IMG_5871

**Review by timurtripp — APPROVED** [review]
For single-column blocks this looks good, and that's mainly what the issue was on about. Willing to merge this if the wrapped multi-column looks like a complex fix that warrants its own issue.

**Comment by patrickbrown-io** [comment]
> For blocks within the same column this looks good, and that's mainly what the issue was on about. Willing to merge this if the wrapped multi-column looks like a complex fix that warrants its own issue.

@timurtripp -- so your screenshot, that's a multi-column collapsing into a single column on mobile? I think that would merit its own issue.

I believe the intent of #820 is the want to use a section, add multiple blocks to it in order to create a single pseudo-block of content. The screenshots in that issue show off a pseudo-Hero Unit built out of two text blocks stacked, without the margin between the two Text blocks.

**Pull request merged**
