### PR TITLE
Mega Menus

### LINKED ISSUE #629: Mega Menu
A few of the higher profile sites, such as /business, use a mega menu in their navigation.

The Express 3.0 version of Mega Menu is a custom entity that can be attached to a specific menu item.

**Fields**

- Label (for admin use only)
- Heading (Displayed at the top of the mega menu and linked to the menu item's url)
- Text Above (WYSIWYG)
- Links (A field collection with no limit)
-- Label (Heading at the top of link list)
-- Link field collection with no limit)
--- Link field (limit 1)
--- Description (text field, limit 1)
- Text Below (WYSIWYG)

**Setup**

- Individual mega menus are created
- mega menus are attached to main menu items via a select menu showing all available mega menus
-- mega menus can be enabled/disabled by a toggle switch on the menu item

**Display**

- The mega menu in 3.0 displays only on desktop browsers. Needs additional testing for mobile menu use.
- Main menu links would get a downward angle icon (https://fontawesome.com/v4/icon/angle-down) to indicate there was a mega menu on that link
- Clicking on the main menu link would display the mega menu, the heading of the main menu is linked to the original menu item's url in order to allow the user to visit that page
- Display of the Links collections are in columns, depending on the number of collection items:
-- <= 3 - 3 columns
-- 4 - 4 columns
-- 5 - 5 columns
-- 6 - 6 columns
-- 3.0 code didn't account for more than that and would default back to 3 columns of links
-- If the Text Above field is used, this is considered another column. For example, Text Above + 3 Link collections would display as 4 columns
-- Text Below is displayed below the link columns

**Screenshots**

Mega Menu Create/Edit Screen
image

Attaching a Mega Menu to a Menu Item
image

Navigation showing Mega Menus are attached to menu items (downward angles indicate which links have mega menus)
image

Mega Menu Expanded
image

### PR DESCRIPTION
**Pull request by jacob-korf**
Closes #629.
Adds a mega menu that can be attached as a block in a menu link.
Entities -> https://github.com/CuBoulder/tiamat-custom-entities/pull/157
Profile - > https://github.com/CuBoulder/tiamat10-profile/pull/180
Template -> https://github.com/CuBoulder/tiamat10-project-template/pull/51

### CODE REVIEW

**Review by timurtripp — CHANGES_REQUESTED** [review]
I'm getting a JavaScript error and broken display of the menu on the mobile view (entire main navigation is missing)

**Comment by timurtripp** [comment]
Columns should be equal width and may need some margin/padding fixes
Screenshot 2024-08-12 at 12 37 53 PM

**Comment by timurtripp** [comment]
Revert the changes in `region--primary-menu.html.twig` and try to keep code spacing / indentation as consistent as possible throughout.

**Comment by timurtripp** [comment]
Clicking the menu results in a `#` being appended to the page URL. It should still link to the correct URL even after being made a Mega Menu, but with a `preventDefault()` call stopping the browser from following the link on click.

**Comment by timurtripp** [comment]
Using the following malicious menu link title:
```
Highhelm Clans19');alert('successfully executed');megaMenuClicked('highhelmclans
```
I'm able to execute arbitrary JavaScript. This is an XSS vulnerability. Please properly sanitize all user input before passing it into scripts.

**Comment by timurtripp** [comment]
On D7, clicking anywhere outside the mega menu hides it. That doesn't seem to work in this version.

**Comment by timurtripp** [comment]
Link `href` is still incorrectly altered by enabling mega menu – this time the attribute is gone completely.

**Comment by timurtripp** [comment]
The HTML `title` attribute you added isn't present on D7, isn't needed for accessibility, and should be removed.

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
