### PR TITLE
Content Sequence Block

### LINKED ISSUE #265: Content Sequence
Content sequences are blocks that contain bits of content that are presented in a user defined order. It may be a timeline of events, or a set of steps to follow.

The same fields are used to display the information in 3 ways: simple horizontal, simple vertical, or advanced (demos: https://www.colorado.edu/demos/web-express/add-bundles/content-sequence#event-advanced-timeline, documentation: https://websupport.colorado.edu/article/409-01-content-sequence-bundle-overview)

Each event, or step contains the following:

- Title
- Link
- WYSIWYG content
- Image
- Video URL
- Start Date (with an option display override)
- End Date (with optional display override)

The advanced display also has a few extra options:

- Scale (.5, 1, 2)
- Description
- Image

The horizontal and advanced require some javascript and some css:

- horizontal - https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_content_sequence_bundle/cu_content_sequence/js/cu-content-sequence-simple-horizontal.js
- advanced - https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_content_sequence_bundle/cu_content_sequence/js/timeline-min.js
- css - https://github.com/CuBoulder/express_mono/tree/dev/modules/custom/cu_content_sequence_bundle/cu_content_sequence/css

Design should follow the demos linked above.

### PR DESCRIPTION
**Pull request by jacob-korf**
Closes #265.
Add the horizontal, vertical, and advanced content sequences.

### CODE REVIEW

**Comment by TeddyBearX** [comment]
Looks good, only a few minor style changes I'd suggest:

### Horizontal

Fix the padding above "Step 1" and change the slider at the top to match the [D7 Express version](https://www.colorado.edu/demos/web-express/add-bundles/content-sequence).
Screen Shot 2023-05-02 at 9 32 56 AM

This should look and work better on mobile.
Screen Shot 2023-05-02 at 9 41 05 AM


### Vertical

The middle line should go all the way to the top as it does in D7 Express. Also fix the padding above "Step 2".
Screen Shot 2023-05-02 at 9 35 55 AM

**Comment by TeddyBearX** [comment]
I'm still seeing some problems with the line here.
IMG_4588

**Review by TeddyBearX — CHANGES_REQUESTED** [review]
### Vertical – ✓

Everything looks good. Nice work!

### Horizontal – Changes needed

Mobile looks much better, I like the swipe to go to the next slide a lot. But there are some issues with the top navigation. ~~I'm getting an alert when I press the arrows that I presume you used for debugging but forgot to take out.~~ It also doesn't automatically scroll to the slide I'm currently on as it should. Finally, if you could style it to match the D7 Express version with width and shadow, that'd look a bit better. I've included screenshots of both to show how the styling differs.
IMG_4591
IMG_4592
edit: Though this is the first iMac it's actually "Step 9" of my Content Sequence, unfortunately the top navigation is out of sync with the slide I'm on.

edit 2: The alerts are no longer appearing so I might've had an old cached version of the script on my end – my bad!

**Review by jcsparks — APPROVED** [review]
Still needs work, but mostly there.  Will ticket out for the next path to continue refinement.

**Pull request merged**
