### PR TITLE
Fixes Search page style regression

### PR DESCRIPTION
**Pull request by timurtripp**
Resolves CuBoulder/tiamat-theme#893

### CODE REVIEW

**Comment by patrickbrown-io** [comment]
Looks better than before but theres some weird overlap with the inputs and the search button or the border. 
The first one is present in the d7 version.

Screenshot 2024-04-26 at 12 53 28 PM

Under the Advanced Search:

Screenshot 2024-04-26 at 12 53 41 PM

**Comment by timurtripp** [comment]
I don't think our users will ever see the advanced search on search pages created using the Google Programmable Search module, but you can double-check that for me.

**Comment by timurtripp** [comment]
Though I guess it wouldn't hurt to have it look right just in case

**Comment by timurtripp** [comment]
Issue with the fields under "Advanced Search" should be fixed now.

**Review by patrickbrown-io — APPROVED** [review]

**Pull request merged**
