### PR TITLE
Updates site footer

### PR DESCRIPTION
**Pull request by timurtripp**
This update:
- [Change] Allows items in the site primary contact info in the site footer to have a bottom margin.
- [Change] Updates the column layout of the site footer.
- [Change] Adds margin between columns in the site footer in case they wrap on a mobile device.

Resolves CuBoulder/tiamat-theme#985

### CODE REVIEW

**Review by jnicholCU — CHANGES_REQUESTED** [review]
This looks good, Tim. 
Can we get some extra gutter padding between the two columns?
I think it's unlikely that they have tons of text in those but in case they do it'd be good to keep them from touching.

**Comment by timurtripp** [comment]
Using Bootstrap gutter padding

**Review by jnicholCU — APPROVED** [review]
Added gutter looks right with the new classes.

**Comment by jnicholCU** [comment]
Merging on Jeremy's go ahead too. Thanks Tim.

**Pull request merged**
