### PR TITLE
Refactor to escape HTML from Article user input on Article List

### LINKED ISSUE #361: Article List – HTML in article titles
Article List doesn't properly escape HTML in article titles, allowing for the possibility of an XSS attack from a trusted article author. Please implement escaping or use `innerText` rather than `innerHTML`. Placing any user input in `innerHTML` is just as dangerous and insecure as using `|raw` in Twig.

### PR DESCRIPTION
**Pull request by patrickbrown-io**
Resolves #361 -- Refactors render to use `innerText` instead of `innerHTML` to assemble list render, protecting from malicious user input

### CODE REVIEW

**Review by TeddyBearX — APPROVED** [review]
Tested, works as expected ✓

**Comment by TeddyBearX** [comment]
However you might've inadvertently changed something with the "read more" link

**Comment by patrickbrown-io** [comment]
> However you might've inadvertently changed something with the "read more" link. I just noticed that it looks different.

Missed adding the class to that for styling -- it's now fixed!

**Comment by TeddyBearX** [comment]
Great. Tested and working with no functional changes unless there are HTML tags in an article title so I'll go ahead and merge this!

**Pull request merged**
