### PR TITLE
Print Stylesheets

### LINKED ISSUE #1101: Print Stylesheets
Apparently the HLC Accreditation process needs to be able to print (likely to PDF) static copies of important webpages as part of that process.  

We'll need to create a set of print media stylesheets to make this process work a little better for them.  

Just looking for a first-pass, best-effort at this point as a starting place and will ticket out required enhancements going forwarded as needed.

### PR DESCRIPTION
**Pull request by jacob-korf**
Closes #1101.
Adds a rudimentary print css style for all pages.

### CODE REVIEW

**Comment by timurtripp** [comment]
My changes to `region--site-information.html.twig` have been reverted, please correct this.

**Comment by timurtripp** [comment]
Seeing some minor text contrast issues with the header, footer, and block styles.
Screenshot 2024-08-02 at 12 23 19 PM
Screenshot 2024-08-02 at 12 23 26 PM

**Review by timurtripp — CHANGES_REQUESTED** [review]
If a region style is applied in Layout Builder the text color is still not well legible. Link text color in the site footer is also still not well legible.

**Comment by timurtripp** [comment]
Or it may be that I'm seeing two footers now, the normal one and the print one.

**Comment by timurtripp** [comment]
The CU logo at the top of the print view isn't correct, it's still the white text version.

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
